FROM python:3.10-slim

WORKDIR /worker

COPY requirements.txt .
RUN pip install --upgrade pip && \
    pip install --default-timeout 3000 --retries 5 -r requirements.txt

COPY src ./src

CMD ["python", "-u", "src/workers/predict_worker.py"] 