version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - ./app/.app.env
    ports:
      - "8000:8000"
    volumes:
      - ./app/src:/app/src
    networks:
      - app_net

  web-proxy:
    image: nginx:latest
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app_net

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    restart: on-failure
    networks:
      - app_net

  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - app_net

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.worker
    env_file:
      - ./worker/worker.env
    volumes:
      - ./worker/src:/worker/src
    depends_on:
      - rabbitmq
      - database
    networks:
      - app_net

  frontend:
    build:
      context: ./frontend-service
      dockerfile: Dockerfile
    depends_on:
      - app
    networks:
      - app_net

networks:
  app_net: {} 