FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libffi-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.worker.txt .
RUN pip install --no-cache-dir -r requirements.worker.txt

COPY src /app/src

RUN mkdir -p /app/logs /app/models

ENV PYTHONPATH=/app

CMD ["python", "-m", "src.workers.ml_worker"] 