FROM python:3.10-slim

WORKDIR /worker

COPY requirements.txt .
RUN pip install --upgrade pip && \
    pip install --default-timeout 3000 --retries 5 -r requirements.txt

COPY src ./src

# Copy example mask files
COPY brain_mask_AHMU1218003.nii.gz .
COPY aneurysm_mask_AHMU1218003.nii.gz .

CMD ["python", "-u", "src/workers/scan3d_worker.py"] 